# Generated by Django 3.1.3 on 2021-01-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_books_is_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
